import { getRawConnection } from '../config/database.js';

export async function createSocietyDB(societyId) {
  const dbName = `society_${societyId.replace(/-/g, '_')}`;
  const conn = await getRawConnection();
  try {
    await conn.execute(`CREATE DATABASE IF NOT EXISTS \`${dbName}\``);
    await conn.execute(`USE \`${dbName}\``);

    const tables = [
      `CREATE TABLE IF NOT EXISTS towers (id VARCHAR(36) PRIMARY KEY, name VARCHAR(255) NOT NULL, totalFloors INT DEFAULT 0, flatsPerFloor INT DEFAULT 0, description TEXT DEFAULT '', status ENUM('active','inactive','under_construction') DEFAULT 'active', createdAt DATETIME DEFAULT CURRENT_TIMESTAMP, updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX idx_name(name))`,
      `CREATE TABLE IF NOT EXISTS flats (id VARCHAR(36) PRIMARY KEY, towerId VARCHAR(36) DEFAULT NULL, towerName VARCHAR(255) DEFAULT '', flatNumber VARCHAR(50) NOT NULL, floor INT DEFAULT 0, type ENUM('1RK','1BHK','2BHK','3BHK','4BHK','5BHK','Penthouse','Shop','Office') DEFAULT '2BHK', area VARCHAR(50) DEFAULT '', ownerName VARCHAR(255) DEFAULT '', ownerPhone VARCHAR(50) DEFAULT '', ownerEmail VARCHAR(255) DEFAULT '', status ENUM('vacant','occupied','rented','under_maintenance') DEFAULT 'vacant', createdAt DATETIME DEFAULT CURRENT_TIMESTAMP, updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY(towerId) REFERENCES towers(id) ON DELETE SET NULL, INDEX idx_towerId(towerId), INDEX idx_status(status))`,
      `CREATE TABLE IF NOT EXISTS residents (id VARCHAR(36) PRIMARY KEY, name VARCHAR(255) NOT NULL, flatNumber VARCHAR(50) DEFAULT '', tower VARCHAR(255) DEFAULT '', phone VARCHAR(50) DEFAULT '', email VARCHAR(255) DEFAULT '', type ENUM('owner','tenant','family') DEFAULT 'owner', status ENUM('active','inactive') DEFAULT 'active', vehicleNumber VARCHAR(50) DEFAULT '', aadhaarNumber VARCHAR(20) DEFAULT '', moveInDate DATE DEFAULT NULL, emergencyContact VARCHAR(50) DEFAULT '', createdAt DATETIME DEFAULT CURRENT_TIMESTAMP, updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX idx_flat(flatNumber))`,
      `CREATE TABLE IF NOT EXISTS complaints (id VARCHAR(36) PRIMARY KEY, title VARCHAR(255) NOT NULL, description TEXT DEFAULT '', category VARCHAR(100) DEFAULT 'general', status ENUM('open','in_progress','resolved','closed') DEFAULT 'open', priority ENUM('low','medium','high','critical') DEFAULT 'medium', reportedBy VARCHAR(255) DEFAULT '', flatNumber VARCHAR(50) DEFAULT '', assignedTo VARCHAR(255) DEFAULT '', createdAt DATETIME DEFAULT CURRENT_TIMESTAMP, updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX idx_status(status))`,
      `CREATE TABLE IF NOT EXISTS notices (id VARCHAR(36) PRIMARY KEY, title VARCHAR(255) NOT NULL, description TEXT DEFAULT '', category VARCHAR(100) DEFAULT 'general', priority ENUM('low','medium','high') DEFAULT 'medium', status ENUM('active','expired','draft') DEFAULT 'active', postedBy VARCHAR(255) DEFAULT '', createdAt DATETIME DEFAULT CURRENT_TIMESTAMP, updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX idx_status(status))`,
      `CREATE TABLE IF NOT EXISTS visitors (id VARCHAR(36) PRIMARY KEY, name VARCHAR(255) NOT NULL, phone VARCHAR(50) DEFAULT '', purpose VARCHAR(255) DEFAULT '', flatNumber VARCHAR(50) DEFAULT '', tower VARCHAR(255) DEFAULT '', status ENUM('checked_in','checked_out','expected','rejected') DEFAULT 'expected', vehicleNumber VARCHAR(50) DEFAULT '', checkInTime DATETIME DEFAULT NULL, checkOutTime DATETIME DEFAULT NULL, approvedBy VARCHAR(255) DEFAULT '', createdAt DATETIME DEFAULT CURRENT_TIMESTAMP, INDEX idx_status(status))`,
      `CREATE TABLE IF NOT EXISTS parking (id VARCHAR(36) PRIMARY KEY, slotNumber VARCHAR(50) NOT NULL, type ENUM('two_wheeler','four_wheeler','visitor','reserved','ev') DEFAULT 'four_wheeler', status ENUM('available','occupied','reserved','maintenance') DEFAULT 'available', vehicleNumber VARCHAR(50) DEFAULT '', vehicleType VARCHAR(50) DEFAULT '', flatNumber VARCHAR(50) DEFAULT '', ownerName VARCHAR(255) DEFAULT '', createdAt DATETIME DEFAULT CURRENT_TIMESTAMP, updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX idx_status(status))`,
      `CREATE TABLE IF NOT EXISTS staff (id VARCHAR(36) PRIMARY KEY, name VARCHAR(255) NOT NULL, role VARCHAR(100) DEFAULT '', phone VARCHAR(50) DEFAULT '', email VARCHAR(255) DEFAULT '', department VARCHAR(100) DEFAULT '', status ENUM('active','inactive','on_leave') DEFAULT 'active', joinDate DATE DEFAULT NULL, salary VARCHAR(50) DEFAULT '', address TEXT DEFAULT '', createdAt DATETIME DEFAULT CURRENT_TIMESTAMP, updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX idx_dept(department))`,
      `CREATE TABLE IF NOT EXISTS vendors (id VARCHAR(36) PRIMARY KEY, name VARCHAR(255) NOT NULL, company VARCHAR(255) DEFAULT '', service VARCHAR(255) DEFAULT '', phone VARCHAR(50) DEFAULT '', email VARCHAR(255) DEFAULT '', status ENUM('active','inactive') DEFAULT 'active', address TEXT DEFAULT '', createdAt DATETIME DEFAULT CURRENT_TIMESTAMP, updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)`,
      `CREATE TABLE IF NOT EXISTS vendor_contracts (id VARCHAR(36) PRIMARY KEY, vendorId VARCHAR(36) DEFAULT NULL, vendorName VARCHAR(255) DEFAULT '', title VARCHAR(255) NOT NULL, startDate DATE DEFAULT NULL, endDate DATE DEFAULT NULL, amount DECIMAL(12,2) DEFAULT 0, status ENUM('active','expired','terminated','pending') DEFAULT 'active', description TEXT DEFAULT '', createdAt DATETIME DEFAULT CURRENT_TIMESTAMP, updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY(vendorId) REFERENCES vendors(id) ON DELETE SET NULL)`,
      `CREATE TABLE IF NOT EXISTS vendor_payments (id VARCHAR(36) PRIMARY KEY, vendorId VARCHAR(36) DEFAULT NULL, vendorName VARCHAR(255) DEFAULT '', amount DECIMAL(12,2) DEFAULT 0, paymentDate DATE DEFAULT NULL, method ENUM('cash','bank_transfer','cheque','upi','online') DEFAULT 'bank_transfer', status ENUM('pending','paid','failed','cancelled') DEFAULT 'pending', receiptNo VARCHAR(100) DEFAULT '', description TEXT DEFAULT '', createdAt DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(vendorId) REFERENCES vendors(id) ON DELETE SET NULL)`,
      `CREATE TABLE IF NOT EXISTS billing (id VARCHAR(36) PRIMARY KEY, flatNumber VARCHAR(50) DEFAULT '', tower VARCHAR(255) DEFAULT '', residentName VARCHAR(255) DEFAULT '', amount DECIMAL(12,2) DEFAULT 0, type ENUM('maintenance','water','electricity','parking','penalty','other') DEFAULT 'maintenance', month VARCHAR(20) DEFAULT '', year INT DEFAULT NULL, dueDate DATE DEFAULT NULL, status ENUM('pending','paid','overdue','partial') DEFAULT 'pending', paidDate DATE DEFAULT NULL, paidAmount DECIMAL(12,2) DEFAULT 0, paymentMethod VARCHAR(50) DEFAULT '', receiptNo VARCHAR(100) DEFAULT '', createdAt DATETIME DEFAULT CURRENT_TIMESTAMP, updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX idx_flat(flatNumber), INDEX idx_status(status))`,
      `CREATE TABLE IF NOT EXISTS billing_payments (id VARCHAR(36) PRIMARY KEY, billingId VARCHAR(36) DEFAULT NULL, flatNumber VARCHAR(50) DEFAULT '', amount DECIMAL(12,2) DEFAULT 0, paymentDate DATETIME DEFAULT CURRENT_TIMESTAMP, method VARCHAR(50) DEFAULT '', transactionId VARCHAR(100) DEFAULT '', receiptNo VARCHAR(100) DEFAULT '', status ENUM('success','failed','pending') DEFAULT 'success', createdAt DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(billingId) REFERENCES billing(id) ON DELETE SET NULL)`,
      `CREATE TABLE IF NOT EXISTS move_requests (id VARCHAR(36) PRIMARY KEY, type ENUM('move_in','move_out') DEFAULT 'move_in', flatNumber VARCHAR(50) DEFAULT '', tower VARCHAR(255) DEFAULT '', residentName VARCHAR(255) DEFAULT '', phone VARCHAR(50) DEFAULT '', moveDate DATE DEFAULT NULL, status ENUM('pending','approved','rejected','completed') DEFAULT 'pending', reason TEXT DEFAULT '', approvedBy VARCHAR(255) DEFAULT '', createdAt DATETIME DEFAULT CURRENT_TIMESTAMP, updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX idx_status(status))`,
      `CREATE TABLE IF NOT EXISTS documents (id VARCHAR(36) PRIMARY KEY, title VARCHAR(255) NOT NULL, category VARCHAR(100) DEFAULT 'general', description TEXT DEFAULT '', fileUrl TEXT DEFAULT '', fileName VARCHAR(255) DEFAULT '', fileSize VARCHAR(50) DEFAULT '', uploadedBy VARCHAR(255) DEFAULT '', status ENUM('active','archived','verified','pending') DEFAULT 'active', createdAt DATETIME DEFAULT CURRENT_TIMESTAMP, updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)`,
      `CREATE TABLE IF NOT EXISTS facilities (id VARCHAR(36) PRIMARY KEY, name VARCHAR(255) NOT NULL, type VARCHAR(100) DEFAULT '', capacity INT DEFAULT 0, status ENUM('available','maintenance','closed','booked') DEFAULT 'available', description TEXT DEFAULT '', location VARCHAR(255) DEFAULT '', timings VARCHAR(255) DEFAULT '', charges DECIMAL(12,2) DEFAULT 0, createdAt DATETIME DEFAULT CURRENT_TIMESTAMP, updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)`,
      `CREATE TABLE IF NOT EXISTS facility_bookings (id VARCHAR(36) PRIMARY KEY, facilityId VARCHAR(36) DEFAULT NULL, facilityName VARCHAR(255) DEFAULT '', bookedBy VARCHAR(255) DEFAULT '', flatNumber VARCHAR(50) DEFAULT '', bookingDate DATE DEFAULT NULL, startTime VARCHAR(20) DEFAULT '', endTime VARCHAR(20) DEFAULT '', purpose VARCHAR(255) DEFAULT '', status ENUM('confirmed','cancelled','completed','pending') DEFAULT 'pending', createdAt DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(facilityId) REFERENCES facilities(id) ON DELETE SET NULL)`,
      `CREATE TABLE IF NOT EXISTS assets (id VARCHAR(36) PRIMARY KEY, name VARCHAR(255) NOT NULL, category VARCHAR(100) DEFAULT '', \`condition\` ENUM('good','fair','poor','new','damaged') DEFAULT 'good', value DECIMAL(12,2) DEFAULT 0, location VARCHAR(255) DEFAULT '', purchaseDate DATE DEFAULT NULL, warrantyExpiry DATE DEFAULT NULL, description TEXT DEFAULT '', createdAt DATETIME DEFAULT CURRENT_TIMESTAMP, updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)`,
      `CREATE TABLE IF NOT EXISTS gate_passes (id VARCHAR(36) PRIMARY KEY, type ENUM('visitor','delivery','cab','service','other') DEFAULT 'visitor', name VARCHAR(255) DEFAULT '', phone VARCHAR(50) DEFAULT '', flatNumber VARCHAR(50) DEFAULT '', purpose VARCHAR(255) DEFAULT '', vehicleNumber VARCHAR(50) DEFAULT '', status ENUM('active','used','expired','cancelled') DEFAULT 'active', validFrom DATETIME DEFAULT CURRENT_TIMESTAMP, validUntil DATETIME DEFAULT NULL, createdBy VARCHAR(255) DEFAULT '', createdAt DATETIME DEFAULT CURRENT_TIMESTAMP, INDEX idx_status(status))`,
      `CREATE TABLE IF NOT EXISTS emergencies (id VARCHAR(36) PRIMARY KEY, type VARCHAR(100) DEFAULT 'general', description TEXT DEFAULT '', reportedBy VARCHAR(255) DEFAULT '', flatNumber VARCHAR(50) DEFAULT '', status ENUM('active','resolved','false_alarm') DEFAULT 'active', resolvedAt DATETIME DEFAULT NULL, resolvedBy VARCHAR(255) DEFAULT '', createdAt DATETIME DEFAULT CURRENT_TIMESTAMP, INDEX idx_status(status))`,
      `CREATE TABLE IF NOT EXISTS announcements (id VARCHAR(36) PRIMARY KEY, title VARCHAR(255) NOT NULL, description TEXT DEFAULT '', category VARCHAR(100) DEFAULT 'general', priority ENUM('low','medium','high') DEFAULT 'medium', status ENUM('active','expired','draft') DEFAULT 'active', postedBy VARCHAR(255) DEFAULT '', createdAt DATETIME DEFAULT CURRENT_TIMESTAMP, updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)`
    ];

    for (const sql of tables) { await conn.execute(sql); }
    console.log(`[DB] Society database created: ${dbName} (21 tables)`);
    return dbName;
  } finally { await conn.end(); }
}
